export const VISAS = [
    { label: 'Thực tập sinh', code: 'TTS' },
    { label: 'Tokutei', code: 'TKT' },
    { label: 'Kỹ sư', code: 'KS' }
]
export const VISA_DETAILS = [
  {
    label: "Thực tập sinh 3 năm",
    parent: "thuc-tap-sinh",
    visa: "Thực tập sinh 3 năm",
    nameAscii: "thuc-tap-sinh-3-nam",
  },
  {
    label: "Thực tập sinh 1 năm",
    parent: "thuc-tap-sinh",
    visa: "Thực tập sinh 1 năm",
    nameAscii: "thuc-tap-sinh-1-nam",
  },
  { label: "Thực tập sinh 3 go", parent: "thuc-tap-sinh", visa: "Thực tập sinh 3 go", nameAscii: "thuc-tap-sinh-3-go" },
  { label: "Đầu Nhật", parent: "dac-dinh", visa: "Tokutei đầu Nhật", nameAscii: "dac-dinh-dau-nhat" },
  { label: "Đầu Việt", parent: "dac-dinh", visa: "Tokutei đầu Việt", nameAscii: "dac-dinh-dau-viet" },
  {
    label: "Đầu Nhật tiếng yếu",
    parent: "dac-dinh",
    visa: "Tokutei đầu Nhật",
    languageLevel: ["N4", "N5", "Không yêu cầu tiếng"],
    nameAscii: "dac-dinh-dau-nhat",
  },
  {
    label: "Đầu Việt tiếng yếu",
    parent: "dac-dinh",
    visa: "Tokutei đầu Việt",
    languageLevel: ["N4", "N5", "Không yêu cầu tiếng"],
    nameAscii: "dac-dinh-dau-viet",
  },
  {
    label: "Đầu Nhật có tiếng",
    parent: "dac-dinh",
    visa: "Tokutei đầu Nhật",
    languageLevel: ["N1", "N2", "N3"],
    nameAscii: "dac-dinh-dau-nhat",
  },
  {
    label: "Đầu Việt có tiếng",
    parent: "dac-dinh",
    visa: "Tokutei đầu Việt",
    languageLevel: ["N1", "N2", "N3"],
    nameAscii: "dac-dinh-dau-viet",
  },
  { label: "Đi mới", parent: "dac-dinh", visa: "Tokutei đi mới", nameAscii: "dac-dinh-di-moi" },
  { label: "Đầu Nhật", parent: "ky-su", visa: "Kỹ sư đầu Nhật", nameAscii: "ky-su-dau-nhat" },
  { label: "Đầu Việt", parent: "ky-su", visa: "Kỹ sư đầu Việt", nameAscii: "ky-su-dau-viet" },
  {
    label: "Đầu Việt không tiếng",
    parent: "ky-su",
    visa: "Kỹ sư đầu Việt",
    languageLevel: ["Không yêu cầu tiếng"],
    nameAscii: "ky-su-dau-viet",
  },
  {
    label: "Đầu Nhật tiếng yếu",
    parent: "ky-su",
    visa: "Kỹ sư đầu Nhật",
    languageLevel: ["N4", "N5", "Không yêu cầu tiếng"],
    nameAscii: "ky-su-dau-nhat",
  },
  {
    label: "Đầu Nhật có tiếng",
    parent: "ky-su",
    visa: "Kỹ sư đầu Nhật",
    languageLevel: ["N1", "N2", "N3"],
    nameAscii: "ky-su-dau-nhat",
  },
  {
    label: "Đầu Việt tiếng yếu",
    parent: "ky-su",
    visa: "Kỹ sư đầu Việt",
    languageLevel: ["N4", "N5", "Không yêu cầu tiếng"],
    nameAscii: "ky-su-dau-viet",
  },
  {
    label: "Đầu Việt có tiếng",
    parent: "ky-su",
    visa: "Kỹ sư đầu Việt",
    languageLevel: ["N1", "N2", "N3"],
    nameAscii: "ky-su-dau-viet",
  },
];